###############################################
#    GENERATED BY scriptFramework_tools.sh    #
###############################################

source "../../scriptFramework.sh"

usage() {
    :
}

declare_env() {
    :
}

check_env() {
    :
}

#####################################
#    DECLARE YOUR FUNCTIONS HERE    #
#####################################

simple_case() {
    mycase="case2"
    
    case $mycase in
        "case1" )
            echo "CASE1"
            ;;
        "case2" )
            echo "CASE2"
            ;;
        "case3" )
            echo "CASE3"
            ;;
    esac

}

complex_case(){
    mycase="case_pattern"
    
    case $mycase in
        *pattern )
            echo "CASE1"
            ;;
        case* )
            echo "CASE2"
            ;;
        "case3" )
            echo "CASE3"
            ;;
    esac
}

case_in_case() {
    mycase="case3"
    
    case $mycase in
        "case1" )
            echo "CASE1"
            ;;
        "case2" )
            echo "CASE2"
            ;;
        "case3" )
            innercase="innercase"
            case $innercase in
                "case1" ) 
                    echo "CASE1"
                    ;;
                "innercase" )
                    echo "INNER CASE"
                    ;;
            esac
            echo "CASE3"
            ;;
    esac
}

none_case() {
    mycase="none"
    
    case $mycase in
        *pattern )
            echo "CASE1"
            ;;
        "case3" )
            echo "CASE3"
            ;;
    esac
}

#####################################

main() {
    breakpoint
    
    simple_case
    none_case
    
    complex_case
    case_in_case
}
