#!/bin/bash
###############################################
#    GENERATED BY scriptFramework_tools.sh    #
###############################################

. "../../scriptFramework.sh"

usage() {
    :
}

declare_env() {
    :
}

check_env() {
    :
}

declare_source() {
    "./included_step_in.sh"
}

#####################################
#    DECLARE YOUR FUNCTIONS HERE    #
#####################################

step_in_1() {
    echo -e "\tSTEP_IN1"
    included_function
    
    
    echo -e "\tSTEP_OUT1"
}

step_in_2() {
    breakpoint
    func_with_parameters "wo" "lo lo"
}

#####################################

main() {
    breakpoint
    echo $1
    echo "MAIN"
    #breakpoint
    step_in_1
    step_in_2
    echo "END MAIN"
}
