###############################################
#    GENERATED BY scriptFramework_tools.sh    #
###############################################

source "../../scriptFramework.sh"

usage() {
    :
}

declare_env() {
    :
}

check_env() {
    :
}

#####################################
#    DECLARE YOUR FUNCTIONS HERE    #
#####################################
simple_while() {
    myvar=0
    
    while [ $myvar != 2 ]; do
        myvar=$((myvar + 1))
        echo $myvar
    done

    logSInfo "END SIMPLE WHILE"
}

while_with_break() {
    myvar=0
    
    while [ $myvar != 4 ]; 
    do
        if [[ $myvar == 1 ]]; then
            break
        fi
        myvar=$((myvar + 1))
        echo $myvar
    done
    
    logSInfo "END BREAK WHILE"
}

while_with_continue() {
    myvar=0
    
    while [ $myvar != 4 ]; do
        if [[ $myvar == 1 ]]; then
            myvar=$((myvar + 3))
            continue
        fi
        myvar=$((myvar + 1))
        echo $myvar
    done
    
    logSInfo "END CONTINUE WHILE"
}

while_in_while() {
    myvar=1
    myInnerVar=7
    
    while [ $myvar != 3 ]; do
        echo "ENTERING LOOP"
        
        while [ $myInnerVar != 0 ]; do
            myInnerVar=$((myvar - 1))
            echo "myInnerVar "$myInnerVar
        done
        
        myvar=$((myvar + 1))
        echo "myvar "$myvar
                
    done
    
    logSInfo "END WHILE_IN_WHILE"
}


#####################################

main() {
    breakpoint
    
    simple_while
    while_with_break
    while_with_continue
    while_in_while
}
