###############################################
#    GENERATED BY scriptFramework_tools.sh    #
###############################################

source "/home/simar/scripts/Script_Framework/scriptFramework.sh"

usage() {
    :
}

declare_env() {
    myvar="wolo"
    mysamevar="wolo"
    myothervar="wala"
}

check_env() {
    :
}

#####################################
#    DECLARE YOUR FUNCTIONS HERE    #
#####################################

simple_if() {
    if [[ $myvar == $mysamevar ]];
    then
        echo "IF"
    fi
    
    if [ $myvar == $myothervar ] ;then
        echo "ELSE"
    fi
}

if_in_if() {
    if [[ $myvar == $mysamevar ]];
    then
        if [[ $myvar == $myothervar ]];
        then
            echo "NOPE"
        else
            echo "IF_IN_IF"
        fi
    fi
}

if_with_else() {
    if [[ $myvar == $myothervar ]];
    then
        echo "IF"
    else
        echo "ELSE"
    fi

}
if_with_simple_elif() {
    if [[ $myvar == $myothervar ]];
    then
        echo "IF"
    elif [[ $myvar == $mysamevar ]]; then
        echo "ELIFOK"
    else
        echo "ELSE"
    fi
    
    echo "FIN IF WITH ELIF"
}

if_with_elif() {
    if [[ $myvar == $myothervar ]];
    then
        echo "IF"
    elif [[ $myvar == $mysamevar ]]; then
        echo "ELIF"
    elif [[ "2" == "3" ]]; then
        echo "HERE DONT WORK"
    else
        echo "ELSE"
    fi
    
    echo "FIN IF WITH ELIF"
}

#####################################

main() {
    echo "MAIN"
    
    breakpoint
    # OUPUT: IF, ELSE, ELIF
    simple_if
    if_with_else
    
    if_with_simple_elif
    if_with_elif # DOESN'T WORK
    
    if_in_if
    
    echo "END MAIN"
}
