###############################################
#    GENERATED BY scriptFramework_tools.sh    #
###############################################

source "../../scriptFramework.sh"

usage() {
    :
}

declare_env() {
    :
}

check_env() {
    :
}

#####################################
#    DECLARE YOUR FUNCTIONS HERE    #
#####################################
simple_until() {
    myvar=0
    
    until [ $myvar == 2 ]; do
        myvar=$((myvar + 1))
        echo $myvar
    done

    logSInfo "END SIMPLE UNTIL"
}

until_with_break() {
    myvar=0
    
    until [ $myvar == 4 ]; 
    do
        if [[ $myvar == 1 ]]; then
            break
        fi
        myvar=$((myvar + 1))
        echo $myvar
    done
    
    logSInfo "END BREAK UNTIL"
}

until_with_continue() {
    myvar=0
    
    until [ $myvar == 4 ]; do
        if [[ $myvar == 1 ]]; then
            myvar=$((myvar + 3))
            continue
        fi
        myvar=$((myvar + 1))
        echo $myvar
    done
    
    logSInfo "END CONTINUE UNTIL"
}

until_in_until() {
    myvar=1
    myInnerVar=7
    
    until [ $myvar == 3 ]; do
        echo "ENTERING LOOP"
        
        until [ $myInnerVar == 0 ]; do
            myInnerVar=$((myvar - 1))
            echo "myInnerVar "$myInnerVar
        done
        
        myvar=$((myvar + 1))
        echo "myvar "$myvar
                
    done
    
    logSInfo "END UNTIL_IN_UNTIL"
}


#####################################

main() {
    breakpoint
    
    simple_until
    until_with_break
    until_with_continue
    until_in_until
}
